### ISSUE TITLE
Length is flakey and incorrect sometimes after flattening:

### ISSUE THREAD

**Issue by Oufattole** [mmcdermott/nested_ragged_tensors#48]
When I run
```python
from nested_ragged_tensors.ragged_numpy import JointNestedRaggedTensorDict
tensors = {
    "code": [[1,2],[3,4],[5,6],[7,8,9,10],[11,12]],
    "time": [0,1,2,3,4],
}
data = JointNestedRaggedTensorDict(raw_tensors=tensors)

print(len(data.flatten()))
```

When I run this 10 times in a jupyter notebook (restarting the session after each run) I get 
$12$ (the expected length)  6/10 runs and $1$ 4/10 runs.

**Comment by mmcdermott** [comment]
I believe this is because the 0-dim bounds are being retained when they should be dropped, and that is a one element list that is sometimes the first key in the unconstrained order of dictionary key iteration. That's why it is roughly 2/3 of the time it is right (if the code or time key are first) and 1/3 of the time wrong (if the bounds key is first)
